### PR TITLE
Implementation of name changing in History section

### PR DESCRIPTION
**Pull request by H-SM**
- [x] Implemented newname feature
- [x] looked over all edges cases in it 
- [x] api called after state change in context, rechecked all the implementation in name change in the server side as well

### CODE REVIEW

**Review by Sid-the-Slothh — APPROVED** [review]
damn you vinay I curse your entire family line to have itchy palms for $10\uparrow\uparrow\uparrow ... 10$  years

**Review by ThapaVinay — APPROVED** [review]

**Comment by H-SM** [comment]
skill issue

**Comment by H-SM** [comment]
skill issue

**Comment by H-SM** [comment]
skill issue

**Comment by H-SM** [comment]
skill issue

**Pull request merged**
